version: '3.8'

services:
  pelosidb:
    build: .
    container_name: pelosidb
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
    restart: unless-stopped
